mail:
  config:
    sendEmailWhenStart: false
    sendEmailWhenError: false
    username: dc.alert@puscene.com
    password: 6a3c7f5c87dZcwKP
    from: dc.alert@puscene.com
    to: liu.yu@puscene.com
    ccList: xu.qing@puscene.com;xu.guanguo@puscene.com;liu.yu@puscene.com;xu.mingxun@puscene.com;qin.yuchen@puscene.com
    bccList:

app:
  register:
      appNames: 001:bbs,002:blog,003:manage
      appKeys: bbs:8facfb8b802c023a89f98f81f813c6ea,blog:c4eo38a96a36c8ba4510c822c0df8e78,manage:954f4c23472378884804d22449abf4af
      publicKeys:
        bbs: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDceYVjb/nZTs/TJqZR7AxzdHZNUOrPSDnJV5ANjlfyKsQs9C6vGuuljfxdyUi14J9IWoIks7jHVaR6vISanoxYB/blOBX7Ukr5XNu5dkVI7RaWxikf/eHQVCrQEL26Z3hCk2K5iRfiQNo68UCnRxRKcvhLHRKvoOWKC3fTv2nAqwIDAQAB
        blog:
        manage:
      privateKeys:
        bbs: MIICdAIBADANBgkqhkiG9w0BAQEFAASCAl4wggJaAgEAAoGBANx5hWNv+dlOz9MmplHsDHN0dk1Q6s9IOclXkA2OV/IqxCz0Lq8a66WN/F3JSLXgn0hagiSzuMdVpHq8hJqejFgH9uU4FftSSvlc27l2RUjtFpbGKR/94dBUKtAQvbpneEKTYrmJF+JA2jrxQKdHFEpy+EsdEq+g5YoLd9O/acCrAgMBAAECfzqQDN5c4ADY7lsn6QXZrXT9em8PD0//31mb6KexJ6srsPA/7CaXAAD5tg8zaBznjWeqoucc1fgcx5PSf2aStrQtMJvfg8y5ND6ZXQ3WZfxdHZ717GoRbjk5DgPLkyXqc/4blAR2V6WHwYlcD09g0ESIB9XgoQsOacMffJI5j4ECQQDwqjwQulVTDftFlNY8ExPkEJH4Y3OyEDYG4fVFhDnhrAiyTz00WNhtD9I7yxf2gdl/QhaiH8sORXDepQTtxMKxAkEA6oXwci+0KKLCmMCqAAWyKoYTk0B/JsFyMeJQEIjGNHm/TBqLPM2v9ChGZCe+m2aZELTS8auphZ0EVUxuBdq4GwJBAIpPS3XRoHe68U1r3DNqQ2QuobU+cp9C8cnC0lLBSwKG+/h90Y7kAH2tOgVjEsJ4naalNJy36NqqzdMmw05iZgECQBcjc9+wOTQxKsXrbFpoNXXgmJnUqTbnqx6k14VqGTQgNvGJROeQ26VZO+ixyyqF6uAtFwrlBuq53S2VRt2pALUCQAI/XH9Yfv/sBiLWwjBCqBn4Gon9g9z5dTwhyCo955XhgOrPOhT/WHJsU+3J0rgDCwvAeBIBzrGvpZEaOayfGQ8=
        blog:
        manage:


appKey:
  keys: mf:8facfb8b802c023a89f98f81f813c6ea,md:c4eo38a96a36c8ba4510c822c0df8e78,mxr:954f4c23472378884804d22449abf4af,wm:c4836clee2ab0ca8618bec6f27e3988b,admin:9b1db8983eddc213b30abcf89f3a4ebf,centerCtrl:1a1db3503eddc213b30abcf89f3a4e3e,cp:5u1db250xeddc253b30abcf89f3a9e3e,pos:6u4db150xedfe253b30abcf89f4a9e3d,express:350ea28b6c394a3f8986452310f8a5e3

env: dev

checkSign: false

config:
  version: 20180707-DEV

alfred-jdbc:
    master: jdbc:mysql://10.0.21.66:3306/alfred?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false&allowMultiQueries=true&useLocalSessionState=true&autoReconnect=true&failOverReadOnly=false&noAccessToProcedureBodies=true&useTimezone=true&serverTimezone=Hongkong
    slave: jdbc:mysql://10.0.21.76:3306/alfred?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false&allowMultiQueries=true&useLocalSessionState=true&autoReconnect=true&failOverReadOnly=false&noAccessToProcedureBodies=true&useTimezone=true&serverTimezone=Hongkong
    username: 9now_dev
    password: 9now.321
    testOnBorrow: true
    initSize: 5
    minIdle: 1
    maxActive: 20

alfred-mobile-jdbc:
    master: jdbc:mysql://10.0.21.66:3306/alfred-mobile?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false&allowMultiQueries=true&useLocalSessionState=true&autoReconnect=true&failOverReadOnly=false&noAccessToProcedureBodies=true&useTimezone=true&serverTimezone=Hongkong
    slave: jdbc:mysql://10.0.21.76:3306/alfred-mobile?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false&allowMultiQueries=true&useLocalSessionState=true&autoReconnect=true&failOverReadOnly=false&noAccessToProcedureBodies=true&useTimezone=true&serverTimezone=Hongkong
    history: jdbc:mysql://10.0.21.76:3306/alfred-mobile-backup?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false&allowMultiQueries=true&useLocalSessionState=true&autoReconnect=true&failOverReadOnly=false
    username: 9now_dev
    password: 9now.321
    testOnBorrow: true
    initSize: 5
    minIdle: 1
    maxActive: 20

alfred-offline-jdbc:
    master: jdbc:mysql://10.0.21.66:3306/alfred-offline?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false&allowMultiQueries=true&useLocalSessionState=true&autoReconnect=true&failOverReadOnly=false&noAccessToProcedureBodies=true&useTimezone=true&serverTimezone=Hongkong
    slave: jdbc:mysql://10.0.21.76:3306/alfred-offline?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false&allowMultiQueries=true&useLocalSessionState=true&autoReconnect=true&failOverReadOnly=false&noAccessToProcedureBodies=true&useTimezone=true&serverTimezone=Hongkong
    username: 9now_dev
    password: 9now.321
    testOnBorrow: true
    initSize: 5
    minIdle: 1
    maxActive: 20

redis:
    maxIdle: 8
    minIdle: 1
    maxTotal: 300
    maxWait: 1000
    timeout: 100000
    testOnBorrow: true
    testOnReturn: true
    passwd:
    sentinel:
      group: sentinel-10.0.19.33-6379
      nodes: 10.0.21.7:6380,10.0.19.172:6379,10.0.19.172:6380

kafka:
    brokers: 10.0.19.71,10.0.19.72,10.0.19.73
    zkNodes: 10.0.19.71,10.0.19.72,10.0.19.73
    zkPort: 2181
    brokerPort: 9092

mq:
   broker:
      url: failover:(tcp://10.0.21.51:61616,tcp://10.0.21.74:61616)?jms.useAsyncSend=true&randomize=false&backup=true&jms.prefetchPolicy.queuePrefetch=1
   username:
   password:
   backup: true

sleuth:
    sampler:
      percentage: 0.1

demo:
  app:
    port: 7031
    maxPageSize: 50

zuul:
  app:
    port: 8030
    ignoreCheckUrls: ping.json,info.json,sf/push,dd/push
    ignoreTokenCheckUrls: NONE
    blacklistUrls: NONE
    maxPageSize: 50
    gatedLaunchMap:
      order-manage-service: true|shopId|3451
      express-service: false|manageShopId|43
      order-cat-service: true|version|1.0
      order-demo-service: true|machine|null
    appblackUrlsMap:
      bbs: NONE

bbs:
  app:
    port: 9000

manage:
  app:
    port: 8031
    maxPageSize: 50
    takeaway:
      elemeAppKey: i51fumWOjN
      elemeAppSecret: dd7b9ee3be5d4c64c7bb07a8860cae71c711e146
      sandBox: true
      meituanAppKey: 100999
      meituanAppSecret: as59ji8fa1xn326d
    sfParentId: MWEE
    sfNewAppId: 1494001262
    sfNewAppKey: c5a56b5263f6d551ac3c1dcc1f3245dc
    menuRsyncAdminUrl: http://10.0.21.203:8087/services/admin/
    adminAppId: admin
    adminAppKey: 9b1db8983eddc213b30abcf89f3a4ebf
    dadaAppKey: dada03de34198345f5d
    dadaAppSecret: 0a2350293b0379e1b19fd42963e8e4eb
    dadaBaseUrl: http://newopen.qa.imdada.cn

cat:
  app:
    port: 8032
    cascadingCategoryRestaurantType: 2|4
    maxPageSize: 50
    openUrl: http://openapi.biz.test.cn/services/developer/findWhiteListShopByAuthId
    shopConfigUrl: http://10.0.21.153:3051/services/cshop/getShopTableConfig
    appId: 1001
    appKey: key
    menuRsyncAdminUrl: http://10.0.21.203:8087/services/admin/
    adminAppId: admin
    adminAppKey: 9b1db8983eddc213b30abcf89f3a4ebf

express:
  app:
    port: 8033
    maxPageSize: 50
    sfUrl: http://218.17.248.249:6810/services/o2oinbound
    sfAesKey: xDc08oqFzYNF/gJD7MjCRvs3Z1FbGVs4
    sfSha512Key: qJd2rm4CMcKPwj5F90r7CNyeFkzx7Cxk
    sfParentId: MWEE
    sfNewUr: http://commit-openic.sf-express.com/open/api/external
    sfNewAppId: 1494001262
    sfNewAppKey: c5a56b5263f6d551ac3c1dcc1f3245dc
    dadaAppKey: dada03de34198345f5d
    dadaAppSecret: 0a2350293b0379e1b19fd42963e8e4eb
    dadaBaseUrl: http://newopen.qa.imdada.cn
    baseUrl: http://dc.cloud-manage.9now.net
    
table:
  app:
    port: 8034
    maxPageSize: 50
    isKoubeiTableCallBack: false
    msgSendUrl2: http://10.0.21.242:3050/services/route/distribute2
    msgSendCallbackType: 1
    msgSendService: 2

mf:
  app:
    port: 8035
    maxPageSize: 50

orderCenter:
  app:
    port: 8036
    maxPageSize: 50

md:
  app:
    port: 8037
    maxPageSize: 50
    pressTestMode: false
    pressTestShopId: 93033
    mdSubmitOrderUrl: http://10.0.21.205:8080/alfred-mobile-api/api/third/order/v2/submit.json
    apiWpos9nowBaseUrl: http://pcdc.winpos.test.cn
    rxMainOrderAutoConfirm: 1
    menuRsyncAdminUrl: http://10.0.21.203:8087/services/admin/
    adminAppId: admin
    adminAppKey: 9b1db8983eddc213b30abcf89f3a4ebf

rx:
  app:
    port: 8038
    maxPageSize: 50
  refund:
    onlineBaseUrl: http://trade.pay.test.cn
    onlineRefundUrl: /refund
    onlineRefundNotifyUrl: http://10.0.19.141:8030/rx/refund/notify
    memRefundUrl: http://cp.test.9now.net/business/app.cardpay.refund
    memRefundDiscountUrl: http://cp.test.9now.net/api/third.platform.cancelDeal/
    onlineRefundTimeout: 3000
    maxResponsiblePartyModifyTime: 1


mwapi:
  editShopUrl: http://10.0.21.153:4051/services/adminShop/shop.editShop
  queryShopListUrl: http://10.0.21.153:4051/services/adminShop/shop.getShopList
  mfConfigUrl: http://10.0.21.153:3051/services/cshop/getSecondPayConfig
  qryShopXmppAccountUrl: http://10.0.21.153:3050/services/bshop/queryShopAccList
  queryCityInfoUrl: http://10.0.21.214:3051/services/api/city.getCityDetail
  xmppServiceUrl: http://10.0.21.153:3050/services/bshop/xmppShopAccount
  shopAuthUrl: http://10.0.21.153:3050/services/bshop/auth
  parseSessionUrl: http://shop.test.cn/rest/business/
  shopBranchsUrl: http://search.test.cn/explainsql
  citysUrl: http://10.0.21.214:3051/services/api/city.getCityList
  crmAppId: 1002
  crmAppKey: 7cc696319dbf41a8d6dcb83380c8fc8b
  apiWpos9nowBase: http://pcdc.winpos.test.cn
  pushDirectUrl: http://10.0.21.242:3050/services/route/direct
  syncFood: true
  pressTestMode: false
  pressTestShopId: 3451
  msgSendUrl2: http://10.0.21.242:3050/services/route/distribute2
  msgSendCallbackType: 1
  msgSendService: 2
  apiCp9nowBase: http://cp.test.9now.net
  cpMethodPreordercust: http://member.soa.test.cn/services/shop/charge/preOrderCharge
  koubeiMdCallBack: true
  koubeiCallback: http://qr-st.api.9now.net/pay/api/KouBei.mdSynOrder
  apiWechatClearShopCarcache: http://dc_api.test.9now.net/api/v1/cart.clearShopCartCache
  editShopInfoUrl: http://10.0.21.153:4051/services/adminShop/shop.editShopInfo

upload:
  url: http://file.test.cn/services/api/file.uploadFile
  home: biztest1
  appId: 1008
  secret: 45e317198948ee64ad80bd3d5df85880
  localTempPath: /pojo/application/temp/
  uploadBasePath: /pojo/application/upload/
